### ISSUE TITLE
parseRequest middleware does not allow empty array parameters

### ISSUE THREAD

**Issue by JamesMGreene** [APIDevTools/swagger-express-middleware#44]
The parseRequest middleware does not allow empty arrays for specified parameters (e.g. `/foo?username=`), even when such a parameter's schema includes `required: false` and/or `minItems: 0`.

```
Error: The "username" query parameter is invalid ("")
JSON Schema validation error.
Invalid type: string (expected array)
    at ono (c:\git\Observer\Apps\ObsNode\node_modules\ono\lib\index.js:62:17)
    at parseParameter (c:\git\Observer\Apps\ObsNode\node_modules\swagger-express-middleware\lib\param-parser.js:148:11)
    at c:\git\Observer\Apps\ObsNode\node_modules\swagger-express-middleware\lib\param-parser.js:35:35
    at Array.forEach (native)
    at parseSimpleParams (c:\git\Observer\Apps\ObsNode\node_modules\swagger-express-middleware\lib\param-parser.js:30:12)
    at ...
```

However, as I understand it from https://github.com/OAI/OpenAPI-Specification/issues/305 and https://github.com/BigstickCarpet/swagger-parser/issues/6, this should result in `[]`.

I can temporarily workaround the problem by adding `default: []` to the schema but that also sets the parameter to `[]` even if it was **not** specified at all (i.e. for both `/foo` and `/foo?username=`).

**Comment by JamesMGreene** [comment]
Proposed PR #45.
