### ISSUE TITLE
Validation error if JSON schema contains multiple data types

### ISSUE THREAD

**Issue by kokog** [APIDevTools/swagger-express-middleware#80]
My JSON schema contains multiple types, something like this:
"xy": {
"type": ["string", "number", "boolean", "array", "object"],
...
}

I have a validation error if I try to use this schema:
Error: Invalid JSON schema type: string,number,boolean,array,object
    at ono (/home/***/node_modules/ono/lib/index.js:62:17)
    at new JsonSchema (/home/***/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:66:11)
    at /home/***/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:524:24
    at /home/***/node_modules/swagger-express-middleware/node_modules/lodash/index.js:3073:15
    at baseForOwn (/home/***/node_modules/swagger-express-middleware/node_modules/lodash/index.js:2046:14)
    at /home/***/node_modules/swagger-express-middleware/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/home/***/node_modules/swagger-express-middleware/node_modules/lodash/index.js:3346:13)
    at serializeObject (/home/***/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:523:7)
    at JsonSchema.serialize (/home/***/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:128:14)
    at serializeArray (/home/***/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:461:29)

Can you add multiple data type functionality to schema validation?

**Comment by BigstickCarpet** [comment]
Yeah, this needs to be added to [Swagger Parser](https://github.com/BigstickCarpet/swagger-parser), which Swagger Express Middleware uses under the hood.  Thanks for pointing this out.  Will add it to the to-do list

**Comment by nodify-at** [comment]
@JamesMessinger Is there any update on this issue? We can not define multiple types for a field described as above. Thanks!

**Comment by JamesMessinger** [comment]
The Swagger/OpenAPI specification does not allow multiple types.  The JSON Schema spec allows multiple types, but Swagger/OpenAPI is a _subset_ of the JSON Schema spec, so there are a few things like this that aren't allowed.
